name: demo_azure
channels:
 - conda-forge
 - defaults
dependencies:
 - python=3.8.11
 - pip
 - pip:
     - streamlit
     - requests
     - pyyaml
     - psycopg2-binary
     - python-dotenv
     - openai
     - pandas
     - numpy
     - pgvector
     - langchain
     - docx2txt
     - docx2pdf
     - tiktoken
     - scikit-learn